### ISSUE TITLE
Handle EPIPE

### ISSUE THREAD

**Issue by ymmt2005** [cybozu-go/log#11]
Users of logger tend to ignore errors returned from logging functions, like this:
```go
func doSomething() {
    err := f()
    if err != nil {
        // ignoring possible error returned by log.Error
        log.Error("failed", map[string]interface{}{
            log.FnError: err.Error(),
        })
    }
}
```

When the underlying output stream went broken and log.Error returns EPIPE,
logs will not be written.  Further, with journald, we see that log.Error will eventually
block forever if continuously write logs after EPIPE.

To prevent disasters, we should change the default behavior so  that cybozu-go/log
detects EPIPE internally and aborts the program.

**Comment by nojima** [comment]
OK

**Comment by ymmt2005** [comment]
Here is the list of general exit codes in UNIX:
http://tldp.org/LDP/abs/html/exitcodes.html

1 and 2 are commonly used.  Therefore, we should choose another, say, 5.
