### ISSUE TITLE
Logging to file

### ISSUE THREAD

**Issue by ymmt2005** [cybozu-go/log#2]
As is often the case with log rotation, the logger should
re-open the log file if it receives a signal such as SIGUSR1.

This package should provide a function to help implementing such a feature.

**Comment by ymmt2005** [comment]
@tfukaya これ誰かにお願いしたいです。私でも、、、いいけど、、、

**Comment by ghost** [comment]
I think this packages does not know specified io.Writer is actually what type,
so someone specifying the writer should re-open the file.
BTW, for the package users, it is helpful to implement a such functionality.
I'll try it.
